//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Portal.MVC.Data.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        public tb_cliente()
        {
            this.tb_usuario = new HashSet<tb_usuario>();
        }
    
        public int idCliente { get; set; }
        public string xRazao { get; set; }
        public string xFantasia { get; set; }
        public string xUrlImg { get; set; }
        public bool stClienteEspecial { get; set; }
    
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
    }
}
