//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Portal.MVC.Data.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_curriculum
    {
        public int idCurriculumVitae { get; set; }
        public string xNome { get; set; }
        public string xTelefone { get; set; }
        public string xCelular { get; set; }
        public string xEmail { get; set; }
        public string xEndereco { get; set; }
        public string xBairro { get; set; }
        public string xCidade { get; set; }
        public string xEstado { get; set; }
        public string xSobreMim { get; set; }
        public string xExperiencia { get; set; }
        public string xFormacao { get; set; }
        public string xAtividadesComplementares { get; set; }
        public string xCompetencias { get; set; }
        public string xObjetivo { get; set; }
        public string xInformacoesComplementares { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
