//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Portal.MVC.Data.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_modulo_item
    {
        public int idModuloItem { get; set; }
        public string xDescricao { get; set; }
        public int idModulo { get; set; }
    
        public virtual tb_modulo tb_modulo { get; set; }
    }
}
