//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Portal.MVC.Data.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_modulo
    {
        public tb_modulo()
        {
            this.tb_modulo_item = new HashSet<tb_modulo_item>();
            this.tb_segmento = new HashSet<tb_segmento>();
        }
    
        public int idModulo { get; set; }
        public string xTitulo { get; set; }
    
        public virtual ICollection<tb_modulo_item> tb_modulo_item { get; set; }
        public virtual ICollection<tb_segmento> tb_segmento { get; set; }
    }
}
