//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Portal.MVC.Data.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_solicitecontato
    {
        public int idSoliciteContato { get; set; }
        public sbyte stObjetivo { get; set; }
        public string xMessage { get; set; }
        public string xTelefone { get; set; }
        public string xCelular { get; set; }
        public string xEmail { get; set; }
    }
}
