//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Portal.MVC.Data.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_segmento
    {
        public tb_segmento()
        {
            this.tb_imagem = new HashSet<tb_imagem>();
            this.tb_modulo = new HashSet<tb_modulo>();
        }
    
        public int idSegmento { get; set; }
        public string xTituloHome { get; set; }
        public string xConteudoHome { get; set; }
        public string xTituloCompleto { get; set; }
        public string xConteudoCompleto { get; set; }
        public string xTituloDiferencial { get; set; }
        public string xConteudoDiferencial { get; set; }
    
        public virtual ICollection<tb_imagem> tb_imagem { get; set; }
        public virtual ICollection<tb_modulo> tb_modulo { get; set; }
    }
}
