//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Portal.MVC.Data.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public tb_usuario()
        {
            this.tb_curriculum = new HashSet<tb_curriculum>();
            this.tb_noticias = new HashSet<tb_noticias>();
        }
    
        public int idUsuario { get; set; }
        public string xNome { get; set; }
        public string xEmail { get; set; }
        public string xSenha { get; set; }
        public string xSenhaSalt { get; set; }
        public string idFaceBook { get; set; }
        public Nullable<int> idCliente { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual ICollection<tb_curriculum> tb_curriculum { get; set; }
        public virtual ICollection<tb_noticias> tb_noticias { get; set; }
    }
}
